name: Dockerization
description: Composite action to configure Docker, ports, networks and build

inputs:
  IMAGE_ARCH:
    required: true
    description: Target platforms for Docker buildx (e.g., linux/amd64)
  COMPOSE_NAME:
    required: true
    description: Prefix for the compose file name
  ENV_NAME:
    required: false
    description: Environment needed to catch the correct Dockerfile
  CACHE:
    required: false
    description: Enable Docker layer caching for faster builds
    default: 'true'
  USE_QEMU:
    required: false
    description: Enable QEMU for cross-platform builds (auto-detect if not set)
    default: 'auto'

outputs:
  IMAGE_NAME:
    value: ${{ steps.docker_config.outputs.IMAGE_NAME }}
  COMPOSE_PORTS:
    value: ${{ steps.port_formatter.outputs.COMPOSE_PORTS }}
  COMPOSE_NETWORKS:
    value: ${{ steps.net_formatter.outputs.COMPOSE_NETWORKS }}
  COMPOSE_VOLUMES:
    value: ${{ steps.volume_formatter.outputs.COMPOSE_VOLUMES }}
  COMPOSE_FILE_NAME:
    value: ${{ steps.docker_config.outputs.COMPOSE_FILE_NAME }}

runs:
  using: "composite"
  steps:

    - name: Make scripts executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/scripts/*.sh

    - name: Docker config
      id: docker_config
      shell: bash
      run: ${{ github.action_path }}/scripts/docker_config.sh
      env:
        COMPOSE_NAME: ${{ inputs.COMPOSE_NAME }}
        ENV_NAME: ${{ inputs.ENV_NAME }}

    - name: Ports formatting from Dockerfile
      id: port_formatter
      shell: bash
      run: ${{ github.action_path }}/scripts/port_formatter.sh
      env:
        DOCKERFILE_PATH: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}

    - name: Network formatting from Dockerfile
      id: net_formatter
      shell: bash
      run: ${{ github.action_path }}/scripts/net_formatter.sh
      env:
        DOCKERFILE_PATH: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}

    - name: Volume formatting from Dockerfile
      id: volume_formatter
      shell: bash
      run: ${{ github.action_path }}/scripts/volume_formatter.sh
      env:
        DOCKERFILE_PATH: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}

    - name: Detect cross-compilation requirement
      id: detect_qemu
      shell: bash
      run: ${{ github.action_path }}/scripts/detect_qemu.sh
      env:
        IMAGE_ARCH: ${{ inputs.IMAGE_ARCH }}
        USE_QEMU: ${{ inputs.USE_QEMU }}

    - name: Set up QEMU
      if: steps.detect_qemu.outputs.needs_qemu == 'true'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.IMAGE_ARCH }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:latest
        buildkitd-flags: --debug

    - name: Cache Docker layers
      if: inputs.CACHE == 'true'
      id: cache-docker
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ steps.detect_qemu.outputs.runner_arch }}-${{ inputs.ENV_NAME }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ steps.detect_qemu.outputs.runner_arch }}-${{ inputs.ENV_NAME }}-
          ${{ runner.os }}-buildx-${{ steps.detect_qemu.outputs.runner_arch }}-
          ${{ runner.os }}-buildx-

    - name: Cache status and recommendations
      if: always()
      shell: bash
      run: ${{ github.action_path }}/scripts/cache_status.sh
      env:
        CACHE_ENABLED: ${{ inputs.CACHE }}
        CACHE_HIT: ${{ steps.cache-docker.outputs.cache-hit }}

    - name: Build Docker image (with cache)
      if: inputs.CACHE == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}
        platforms: ${{ inputs.IMAGE_ARCH }}
        tags: ${{ steps.docker_config.outputs.IMAGE_NAME }}:${{ steps.docker_config.outputs.DOCKER_TAG }}
        outputs: type=docker,dest=${{ steps.docker_config.outputs.IMAGE_NAME }}.tar
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Build Docker image (without cache)
      if: inputs.CACHE != 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}
        platforms: ${{ inputs.IMAGE_ARCH }}
        tags: ${{ steps.docker_config.outputs.IMAGE_NAME }}:${{ steps.docker_config.outputs.DOCKER_TAG }}
        outputs: type=docker,dest=${{ steps.docker_config.outputs.IMAGE_NAME }}.tar

    - name: Build summary
      if: always()
      shell: bash
      run: ${{ github.action_path }}/scripts/build_summary.sh
      env:
        IMAGE_NAME: ${{ steps.docker_config.outputs.IMAGE_NAME }}
        DOCKER_TAG: ${{ steps.docker_config.outputs.DOCKER_TAG }}
        COMPOSE_FILE_NAME: ${{ steps.docker_config.outputs.COMPOSE_FILE_NAME }}
        COMPOSE_PORTS: ${{ steps.port_formatter.outputs.COMPOSE_PORTS }}
        COMPOSE_NETWORKS: ${{ steps.net_formatter.outputs.COMPOSE_NETWORKS }}
        COMPOSE_VOLUMES: ${{ steps.volume_formatter.outputs.COMPOSE_VOLUMES }}
        IMAGE_ARCH: ${{ inputs.IMAGE_ARCH }}
        CACHE_ENABLED: ${{ inputs.CACHE }}
        NEEDS_QEMU: ${{ steps.detect_qemu.outputs.needs_qemu }}
        RUNNER_ARCH: ${{ steps.detect_qemu.outputs.runner_arch }}

    - name: Move Docker cache
      if: always() && inputs.CACHE == 'true'
      shell: bash
      run: |
        if [ -d "/tmp/.buildx-cache-new" ]; then
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          echo "✅ Cache moved successfully"
        else
          echo "⚠️  No new cache directory found, skipping move"
        fi