name: Dockerization
description: Composite action to configure Docker, ports, networks and build

inputs:
  IMAGE_ARCH:
    required: true
    description: Target platforms for Docker buildx (e.g., linux/amd64)
  COMPOSE_NAME:
    required: true
    description: Prefix for the compose file name
  ENV_NAME:
    required: true
    description: Environment needed to catch the correct Dockerfile

outputs:
  IMAGE_NAME:
    value: ${{ steps.docker_config.outputs.IMAGE_NAME }}
  COMPOSE_PORTS:
    value: ${{ steps.port_formatter.outputs.COMPOSE_PORTS }}
  COMPOSE_NETWORKS:
    value: ${{ steps.net_formatter.outputs.COMPOSE_NETWORKS }}
  COMPOSE_VOLUMES:
    value: ${{ steps.volume_formatter.outputs.COMPOSE_VOLUMES }}
  COMPOSE_FILE_NAME:
    value: ${{ steps.docker_config.outputs.COMPOSE_FILE_NAME }}

runs:
  using: "composite"
  steps:

    - name: Make scripts executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/scripts/*.sh

    - name: Docker config
      id: docker_config
      shell: bash
      run: ${{ github.action_path }}/scripts/docker_config.sh
      env:
        COMPOSE_NAME: ${{ inputs.COMPOSE_NAME }}
        ENV_NAME: ${{ inputs.ENV_NAME }}

    - name: Ports formatting from Dockerfile
      id: port_formatter
      shell: bash
      run: ${{ github.action_path }}/scripts/port_formatter.sh
      env:
        DOCKERFILE_PATH: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}

    - name: Network formatting from Dockerfile
      id: net_formatter
      shell: bash
      run: ${{ github.action_path }}/scripts/net_formatter.sh
      env:
        DOCKERFILE_PATH: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}

    - name: Volume formatting from Dockerfile
      id: volume_formatter
      shell: bash
      run: ${{ github.action_path }}/scripts/volume_formatter.sh
      env:
        DOCKERFILE_PATH: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ steps.docker_config.outputs.DOCKERFILE_PATH }}
        platforms: ${{ inputs.IMAGE_ARCH }}
        tags: ${{ steps.docker_config.outputs.IMAGE_NAME }}:${{ steps.docker_config.outputs.DOCKER_TAG }}
        outputs: type=docker,dest=${{ steps.docker_config.outputs.IMAGE_NAME }}.tar
